damage-display:
  # Do you want this feature enabled? [true/false]
  enabled: true
  # How long will the hologram stay in ticks
  duration: 40
  # Damage placeholder: {damage}
  # Animations and Placeholders DO work here
  appearance: '&c{damage}'
  # Appearance of the damage, if the damage is critical
  # Animations and Placeholders DO work here
  # Damage placeholder: {damage}
  critical-appearance: '&4&lCrit!&4 {damage}'
  # Height offset for spawned hologram
  height-offset: 0.0
  # Do you want to display damage for players? [true/false]
  players: true
  # Do you want to display damage for mobs? [true/false]
  mobs: true
  # Do you want to display 0 (or less) damage? [true/false]
  show-zero-damage: true

healing-display:
  # Do you want this feature enabled? [true/false]
  enabled: true
  # How long will the hologram stay in ticks
  duration: 40
  # Heal placeholder: {heal}
  # Animations and Placeholders DO work here
  appearance: '&a+ {heal}'
  # Height offset for spawned hologram
  height-offset: 0.0
  # Do you want to display healing for players? [true/false]
  players: true
  # Do you want to display healing for mobs? [true/false]
  mobs: true