name: Build and Release

on:
  push:
    branches:
      - 'master'
    paths:
      - 'pom.xml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: 8

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Start Spigot Server
      run: |
        curl -o spigot.jar https://cdn.getbukkit.org/spigot/spigot-1.16.5.jar
        java -jar spigot.jar --eula=true

    - name: Execute Minecraft Commands
      run: |
        screen -S minecraft -d -m java -Xmx2G -jar spigot.jar --eula=true nogui
        sleep 5
        screen -r minecraft -X stuff "dh$(printf \\r)"
        screen -r minecraft -X stuff "dh test$(printf \\r)"
        screen -r minecraft -X stuff "stop$(printf \\r)"
        while pgrep -u root -f "java -Xmx2G -jar spigot.jar --eula=true nogui" > /dev/null; do sleep 1; done
        
